export const FORM = [
  {
    label: 'First Name',
    type: 'text',
    value: '',
    placeholder: 'Enter your first name',
    arkey: 'firstName',
    required: true,
    isEditable: true,
  },
  {
    label: 'Last Name',
    type: 'text',
    options: [],
    value: '',
    placeholder: 'Enter your last name',
    arkey: 'lastName',
    required: true,
    isEditable: true,
  },

  {
    label: 'Mobile',
    type: 'tel',
    options: [],
    value: '',
    placeholder: '0412345678',
    arkey: 'mobile',
    required: true,
    pattern: '^04[0-9]{8}$',
    isEditable: true,
  },
  {
    label: 'Email',
    type: 'email',
    options: [],
    value: '',
    placeholder: 'john23@gmail.com',
    arkey: 'email',
    required: true,
    isEditable: true,
  },
  {
    label: 'Address',
    type: 'text',
    options: [],
    value: '',
    required: true,
    placeholder: 'Enter your Address',
    arkey: 'address',
    isEditable: true,
  },
  {
    label: 'City',
    type: 'text',
    options: [],
    value: '',
    required: true,
    placeholder: 'Enter City Name',
    arkey: 'city',
    isEditable: true,
  },
  {
    label: 'State',
    type: 'select',
    options: [
      {
        label: 'New South Wales',
        value: 'NSW',
      },
      {
        label: 'Victoria',
        value: 'VIC',
      },
      {
        label: 'Queensland',
        value: 'QLD',
      },
      {
        label: 'South Australia',
        value: 'SA',
      },
      {
        label: 'Western Australia',
        value: 'WA',
      },
      {
        label: 'Tasmania',
        value: 'TAS',
      },
      {
        label: 'Northern Territory',
        value: 'NT',
      },
      {
        label: 'Australian Capital Territory',
        value: 'ACT',
      },
    ],
    value: '',
    required: true,
    placeholder: 'Select state',
    arkey: 'state',
    isEditable: true,
  },
  {
    label: 'Postal Code',
    type: 'text',
    options: [],
    value: '',
    required: true,
    placeholder: 'Enter zip code',
    arkey: 'postalCode',
    pattern: '^[0-9]{4}$',
    isEditable: true,
  },
  {
    label: 'Street',
    type: 'text',
    options: [],
    value: '',
    required: false,
    placeholder: 'Enter street details',
    arkey: 'street',
    isEditable: true,
  },
  {
    label: 'Business Name',
    type: 'text',
    options: [],
    value: '',
    placeholder: 'Provide business name',
    arkey: 'businessName',
    required: true,
    isEditable: true,
  },
  {
    label: 'ABN Id',
    type: 'text',
    placeholder: 'Enter Business ABN',
    value: '',
    required: true,
    arkey: 'abn',
    isEditable: true,
  },
  {
    label: 'Business Logo',
    type: 'file',
    options: [],
    value: '',
    placeholder: 'upload logo of business',
    arkey: 'businessLogo',
    required: false,
    isEditable: true,
  },
  {
    label: 'Company Website',
    type: 'text',
    options: [],
    value: '',
    placeholder: 'www.companyweb.in',
    arkey: 'companyWebsite',
    required: false,
    isEditable: true,
  },
  {
    label: 'Business Description',
    type: 'textArea',
    options: [],
    value: '',
    placeholder: 'Detail about the business',
    arkey: 'businessDescription',
    required: true,
    isEditable: true,
  },
];
